---
title: "DVOREF_Group_8"
author: "Mihkmihk"
date: "2024-02-15"
output: html_document
---

```{r setup, include=FALSE}
library("stats")
library("tidyverse")
library("ggplot2")
library("dplyr")


group_8_data <- read_csv("../Group_8/Group_8.csv")

group8_df <-
  group_8_data %>% 
  mutate(across(where(is.character), as.factor)) 

resp_lvl <- c("Strongly Disagree", "Disagree", "Agree", "Strongly Agree")

group8_df$Gender <- factor(group8_df$Gender,
                           levels = c("Male", "Female"))


group8_df$`Skin Tone` <- ordered(group8_df$`Skin Tone`,
                            levels = c("Dark", "Fair", "Medium", "Light"))

group8_df$`Skin Type` <- factor(group8_df$`Skin Type`, 
                                levels = c("Combination", "Dry", 
                                           "Normal", "Oily", "Sensitive"))

# group8_df$Q2 <- ordered(group8_df$`Q2`, levels = resp_lvl)
# group8_df$Q3 <- ordered(group8_df$`Q3`, levels = resp_lvl)
# group8_df$Q4 <- ordered(group8_df$`Q4`, levels = resp_lvl)
# group8_df$Q5 <- ordered(group8_df$`Q5`, levels = resp_lvl)
# group8_df$Q6 <- ordered(group8_df$`Q6`, levels = resp_lvl)
# group8_df$Q7 <- ordered(group8_df$`Q7`, levels = resp_lvl)


group8_df <-
  group8_df %>% 
    mutate(across(Q2:Q7, ~ordered(., levels = resp_lvl)))
```

```{r}
gender_colors <- c("paleturquoise2", "lightpink1")

group8_df %>% 
  group_by(Gender) %>%
  ggplot(aes(factor(Gender, levels = c("Male", "Female")), fill = Gender)) +
  geom_text(stat='count',
            aes(label = after_stat(count)),
                size = 5, color = "black", nudge_y = 2) +
  geom_bar(width = 0.5, show.legend = FALSE) +
  labs(x = "Gender",
       y = "Number of Respondents",
       title = "Number of Respondents by Gender") +
  scale_fill_manual(values = gender_colors, 
                    guide = guide_legend(reverse = TRUE)) + 
  theme(
    plot.title.position = "panel",
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_blank(), 
    axis.line = element_line(colour = "black"),
    plot.title = element_text(margin = margin(b=12),
                              hjust = 0.5,
                              vjust = -125,
                              size = 20),
    plot.margin = margin(b = 35),
    aspect.ratio = 1,
    strip.background = element_blank(),
    strip.placement = "outside",
    axis.text = element_text(size = 13,
                             color = "black",
                             face = "plain",
                             vjust = -0.8,
                             margin = margin(b = 20)), 
    axis.title = element_text(size = 16),
    strip.text.x =  element_text(size = 14)
    )
```


``` Testing the Effectiveness of the Radiance of ```
```Dragon Fruit as a Natural Beauty Note: the Cheeks Cream Blush On ```

```{r}
# 1.) To what extent does dragon fruit effectively serve as a cheek blush, and how consistent is it in delivering the desired blush effect in comparison to traditional makeup products?



```


```{r}
# 2.) What are the implications for different skin types, including the risk of skin sensitivities, allergic reactions, or irritations when using dragon fruit as a blush?

library("MASS")
# skin tone explained by Age, Skin Type, Gender and Q1
skinTone_polr <- polr(`Skin Tone` ~ Age + `Skin Type` + Gender + Q1, data = group8_df, Hess=TRUE)
summary(skinTone_polr)
cTable_skinTone <- coef(summary(skinTone_polr))
p_skinTone <- pnorm(abs(cTable_skinTone[, "t value"]), lower.tail = FALSE) * 2
cTable_p_skinTone <- cbind(cTable_skinTone, "p value" = p_skinTone)
cTable_p_skinTone

## odds ratios
exp(coef(skinTone_polr))

detach("package:MASS", unload = TRUE)
```


```{r}
summary(polr(`Skin Tone` ~ Q2, data = group8_df, Hess=TRUE))
summary(polr(Q3 ~ `Skin Tone`, data = group8_df, Hess=TRUE))
summary(polr(Q4 ~ `Skin Tone`, data = group8_df, Hess=TRUE))
summary(polr(Q5 ~ `Skin Tone`, data = group8_df, Hess=TRUE))
summary(polr(Q6 ~ `Skin Tone`, data = group8_df, Hess=TRUE))
summary(polr(Q7 ~ `Skin Tone`, data = group8_df, Hess=TRUE))
```




